language: python
python:
   - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  #- postgresql
before_script:
  #- psql -c "CREATE DATABASE bucketlist_test_db;" -U postgres
  #- psql -c "CREATE USER kiarie WITH PASSWORD '7194';" -U postgres
env:
  #- SECRET_KEY="aX5bqx7djw3Hm1pAz2N8DQOzX3s" DATABASE_TEST_URL="postgres://kiarie:7194@localhost/bucketlist_test_db"
script:
  - python -m pytest --cov=app/api
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)